# Pytorch exercises

Exercise 1: Write a PyTorch code to create a tensor of size (3, 3) filled with random values between 0 and 1.

In [3]:
import torch

tensor1 = torch.rand(3, 3)
print(tensor1)

tensor([[0.2182, 0.6221, 0.5056],
        [0.2018, 0.4751, 0.0407],
        [0.6243, 0.4082, 0.5205]])


Exercise 2:
Create a tensor of size (5, 2) filled with zeros.

In [5]:
tensor2 = torch.zeros(5, 2)
print(tensor2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


Exercise 3:
Implement a PyTorch code to multiply two tensors of size (2, 3) and (3, 4) respectively.

In [7]:
tensor3a = torch.randn(2, 3)
tensor3b = torch.randn(3, 4)
result = torch.mm(tensor3a, tensor3b)
print(result)

tensor([[-0.4332, -0.6936,  0.9672, -0.8428],
        [-0.0693, -0.0397,  0.9619, -0.1997]])


Exercise 4:
Create a PyTorch tensor with values ranging from 5 to 10.

In [9]:
tensor4 = torch.arange(5, 11)
print(tensor4)

tensor([ 5,  6,  7,  8,  9, 10])


Exercise 5:
Write a PyTorch code to compute the mean of a tensor.

In [11]:
tensor5 = torch.randn(3, 3)
mean_value = torch.mean(tensor5)
print(mean_value)

tensor(-0.1976)


Exercise 6:
Implement a PyTorch code to compute the element-wise product of two tensors of the same size.

In [13]:
tensor6a = torch.randn(2, 2)
tensor6b = torch.randn(2, 2)
result6 = torch.mul(tensor6a, tensor6b)
print(result6)

tensor([[ 0.0989, -0.1574],
        [ 0.6624,  0.1888]])


Exercise 7:
Create a PyTorch tensor with values sampled from a normal distribution with mean 0 and standard deviation 1.

In [15]:
tensor7 = torch.randn(3, 3)
print(tensor7)

tensor([[ 0.8983, -1.1774,  0.2870],
        [ 0.5858,  0.7028,  0.8054],
        [-1.1134,  0.9434, -1.9639]])


Exercise 8:
Write a PyTorch code to find the maximum value in a tensor.

In [17]:
tensor8 = torch.randn(3, 3)
max_value = torch.max(tensor8)
print(max_value)

tensor(1.1131)


Exercise 9:
Implement a PyTorch code to compute the cross entropy loss between predicted values and target values.

In [19]:
import torch.nn.functional as F

predicted = torch.randn(3, 5)
target = torch.randint(5, (3,), dtype=torch.long)
loss = F.cross_entropy(predicted, target)
print(loss)

tensor(2.0503)


Exercise 10: Create a PyTorch tensor and then convert it to a NumPy array.

In [21]:
import numpy as np

tensor10 = torch.randn(3, 3)
numpy_array = tensor10.numpy()
print(numpy_array)

[[ 0.8135336   1.1654226   0.4304858 ]
 [-1.2077936  -0.76298255 -0.12160286]
 [ 0.3398758  -0.41346115  0.6855036 ]]


Exercise 11:
Write a PyTorch code to perform a matrix transpose operation on a tensor.

In [23]:
tensor11 = torch.randn(3, 2)
transposed_tensor = torch.transpose(tensor11, 0, 1)
print(transposed_tensor)

tensor([[ 0.8470, -0.2229,  0.1899],
        [ 1.3707,  0.1109,  1.1725]])


Exercise 12:
Implement a PyTorch code to concatenate two tensors along a specified dimension.

In [25]:
tensor12a = torch.randn(3, 2)
tensor12b = torch.randn(3, 2)
concatenated_tensor = torch.cat((tensor12a, tensor12b), dim=1)
print(concatenated_tensor)

tensor([[-0.6639, -1.0550, -1.2528, -0.5588],
        [ 0.5661,  0.7213, -1.0413,  0.1325],
        [ 0.3294, -1.3455, -1.1731, -0.1193]])


Exercise 13:
Create a PyTorch tensor and then convert it to a CUDA tensor if CUDA is available.

In [27]:
tensor13 = torch.randn(3, 3)
if torch.cuda.is_available():
    tensor13_cuda = tensor13.cuda()
    print(tensor13_cuda)
else:
    print("CUDA is not available.")

CUDA is not available.


Exercise 14:
Write a PyTorch code to find the indices of non-zero elements in a tensor.

In [29]:
tensor14 = torch.tensor([0, 1, 0, 2, 0, 3])
nonzero_indices = torch.nonzero(tensor14)
print(nonzero_indices)

tensor([[1],
        [3],
        [5]])


Exercise 15:
Implement a PyTorch code to perform element-wise exponentiation on a tensor.

In [31]:
tensor15 = torch.randn(3, 3)
exponentiated_tensor = torch.exp(tensor15)
print(exponentiated_tensor)

tensor([[1.2789, 3.0478, 9.3578],
        [0.0257, 0.5923, 0.5507],
        [0.5691, 1.7819, 0.5345]])


Exercise 16:
Create a PyTorch tensor and then reshape it into a tensor of different dimensions.

In [33]:
tensor16 = torch.arange(9)
reshaped_tensor = tensor16.reshape(3, 3)
print(reshaped_tensor)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


Exercise 17:
Write a PyTorch code to compute the cosine similarity between two tensors.

In [35]:
tensor17a = torch.randn(3, 3)
tensor17b = torch.randn(3, 3)
cos_sim = torch.nn.functional.cosine_similarity(tensor17a.flatten(), tensor17b.flatten(), dim=0)
print(cos_sim)

tensor(0.2285)


Exercise 18: Implement a PyTorch code to perform element-wise logarithm on a tensor.

In [37]:
tensor18 = torch.randn(3, 3)
logarithm_tensor = torch.log(tensor18)
print(logarithm_tensor)

tensor([[-0.3301,  0.1260,  0.3024],
        [    nan,     nan, -3.1455],
        [    nan, -2.3709, -1.4736]])


Exercise 19:
Create a PyTorch tensor and then calculate its standard deviation.

In [39]:
tensor19 = torch.randn(3, 3)
std_dev = torch.std(tensor19)
print(std_dev)

tensor(1.2114)


Exercice 20: Write a PyTorch code to compute the Frobenius norm of a tensor.

In [41]:
tensor20 = torch.randn(3, 3)
frobenius_norm = torch.norm(tensor20, p='fro')
print(frobenius_norm)

tensor(2.5453)
